<tr>
    <td><a title="<?php echo $this->translate('Edit'); ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $this->id)); ?>"><?php echo $this->domain; ?></a></td>
    <td><?php echo $this->duration; ?></td>
    <td><?php echo $this->cost; ?></td>
    <td><?php echo jdtogregorian($this->register_date + $this->duration * 31); ?></td>
    <td>
        <a title="<?php echo $this->translate('Edit'); ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $this->id)); ?>"><img alt="<?php echo $this->translate('Edit'); ?>" src="<?php echo $this->baseUrl() . '/sites/office-web-admin/images/icons/16/aspnet/edit.gif'; ?>" /></a>
        <a title="<?php echo $this->translate('Delete'); ?>" href="<?php echo $this->url(array('action' => 'delete', 'id' => $this->id)); ?>"><img alt="<?php echo $this->translate('Delete'); ?>" src="<?php echo $this->baseUrl() . '/sites/office-web-admin/images/icons/16/aspnet/delete.gif'; ?>" /></a>
    </td>
</tr>