<div class="info-bar">
    <img class="plus" src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/plus.png'); ?>" />
    <div class="slider" id="slider"></div>
    <img class="minus" src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/minus.png'); ?>" />
    <div class="path"><a href="#">jsadgjhgsad</a> > <a href="#">sadgsadjgsajd</a> > <a href="#">jasgdjgsadjhsad</a>z</div>
    <div class="info">dskjagdhsagd</div>
</div>