<h2><?php echo $this->translate("Admin Panel"); ?></h2>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'advertismentadmin')); ?>">
    <img alt="<?php echo $this->translate('advertisment'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/advertisment.png") ?>" /><br/>
    <?php echo $this->translate("Advertisment"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'multimedia')); ?>">
    <img alt="<?php echo $this->translate('multimedia'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/multimedia.png") ?>" /><br/>
    <?php echo $this->translate("Multimedia"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'web')); ?>">
    <img alt="<?php echo $this->translate('web'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/web.png") ?>" /><br/>
    <?php echo $this->translate("Web"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'content')); ?>">
    <img alt="<?php echo $this->translate('content'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/content.png") ?>" /><br/>
    <?php echo $this->translate("Content"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'customer')); ?>">
    <img alt="<?php echo $this->translate('customer'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/customer.png") ?>" /><br/>
    <?php echo $this->translate("Customer"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'article')); ?>">
    <img alt="<?php echo $this->translate('article'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/article.png") ?>" /><br/>
    <?php echo $this->translate("Article"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'user')); ?>">
    <img alt="<?php echo $this->translate('user'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/user.png") ?>" /><br/>
    <?php echo $this->translate("User"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'menu')); ?>">
    <img alt="<?php echo $this->translate('menu'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/menu.png") ?>" /><br/>
    <?php echo $this->translate("Menu"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'setting')); ?>">
    <img alt="<?php echo $this->translate('setting'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/setting.png") ?>" /><br/>
    <?php echo $this->translate("Setting"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'mail')); ?>">
    <img alt="<?php echo $this->translate('mail'); ?>" src="<?php echo $this->baseUrl("sites/monasebat/images/icons/mail.png") ?>" /><br/>
    <?php echo $this->translate("Mail"); ?>
</a>