<div class="title_bar">
    Webpanelzf Admin Panel
    <a href="<?php echo $this->url(array('action' => 'index')); ?>"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/home.png'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/gear.png'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/help.png'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/info.png'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/warning.png'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/16/exit.png'); ?>" /></a>
</div>
<div class="controller-bar">
    <ul>
        <li id="bar-1"><a href="#">asd</a></li>
        <li id="bar-2" class="active"><a href="#">dsad</a></li>
        <li id="bar-3"><a href="#">asd</a></li>
    </ul>
</div>
<div class="action-bar hidden" id="action-bar-1">
    <div class="box">
        <a class="icon active"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/add.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
    </div>
    <div class="box">
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/add.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
    </div>
</div>
<div class="action-bar hidden" id="action-bar-2">
    <div class="box">
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/add.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
    </div>
</div>
<div class="action-bar hidden" id="action-bar-3">
    <div class="box">
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/add.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
        <a class="icon"><img src="<?php echo $this->baseUrl('sites/office-web-admin/images/icons/32/edit.png'); ?>" /><br/>dskjfh</a>
    </div>
</div>