<?php if ($this->pageCount){
    $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    unset($params['module']);
    unset($params['controller']);
    unset($params['action']);
?>
<div class="paginationControl">
    <!-- Previous page link -->
<?php if (isset($this->previous)){ ?>
  <a href="<?php echo $this->url(array_merge(
      $params, array('page' => $this->previous))); ?>">
    &lt; <?php echo $this->translate('Previous'); ?>
  </a> |
<?php } else { ?>
  <span class="disabled">&lt; <?php echo $this->translate('Previous'); ?></span> |
<?php } ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page){ ?>
  <?php if ($page != $this->current){ ?>
    <a href="<?php echo $this->url(array_merge($params,
        array('page' => $page))); ?>">
        <?php echo $page; ?>
    </a> |
  <?php } else { ?>
    <?php echo $page; ?> |
  <?php }}?>

<!-- Next page link -->
<?php if (isset($this->next)){ ?>
  <a href="<?php echo $this->url(
      array_merge($params, array('page' => $this->next))); ?>">
    <?php echo $this->translate('Next'); ?> &gt;
  </a>
<?php } else { ?>
  <span class="disabled"><?php echo $this->translate('Next'); ?> &gt;</span>
<?php } ?>
</div>
<?php } ?>