<div class="menubox">
    <?php echo $this->translate('Do you want to delete this node?'); ?><br/>
    <div class="tools">
        <a class="icon-yes" title="<?php echo $this->translate('yes'); ?>" href="<?php echo $this->url(array('accept'=>TRUE)); ?>"></a>
        <a class="icon-no" title="<?php echo $this->translate('no'); ?>" href="<?php echo $this->url(array('accept'=>FALSE)); ?>"></a>
    </div>
</div>