<?php
$this->headTitle($this->translate('Webpanelzf Web Admin'), $setType = 'PREPEND');
$this->headTitle()->setSeparator(' :: ');
$this->headScript()->appendFile($this->baseUrl('sites/office-web-admin/script/jquery-1.4.2.min.js'))
        ->appendFile($this->baseUrl('sites/office-web-admin/script/jquery-ui-1.8.5/js/jquery-ui-1.8.5.custom.min.js'))
        ->appendFile($this->baseUrl('sites/office-web-admin/script/core.js'));
$this->headLink()->headLink(array('rel' => 'favicon', 'href' => $this->baseUrl('favicon.ico')), 'PREPEND')
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/style/style.css'))
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/style/controller.css'))
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/style/action.css'))
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/style/body.css'))
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/style/info-bar.css'))
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/style/list.css'))
        ->appendStylesheet($this->baseUrl('sites/office-web-admin/script/jquery-ui-1.8.5/css/ui-lightness/jquery-ui-1.8.5.custom.css'));

$this->layout()->top = $this->action('top', 'indexadmin', 'default');
$this->layout()->bottom = $this->action('bottom', 'indexadmin', 'default');

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php
        echo $this->headTitle();
        echo $this->headScript();
        echo $this->headLink();
        ?>
    </head>
    <body>
        <?php echo $this->layout()->top; ?>
        <div class="body">
            <div class="body-inner">
                <div class="body-main">
                    <div class="body-main-inner">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->layout()->bottom; ?>
    </body>
</html>