<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'planadmin')); ?>">
    <img alt="<?php echo $this->translate('Plan'); ?>" src="<?php echo $this->baseUrl("sites/office-web-admin/images/icons/128/ultimategnome/plan.png") ?>" /><br/>
    <?php echo $this->translate("Plan"); ?>
</a>
<a class="admin_index_icon" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'customeradmin')); ?>">
    <img alt="<?php echo $this->translate('Customer'); ?>" src="<?php echo $this->baseUrl("sites/office-web-admin/images/icons/128/ultimategnome/customer.png") ?>" /><br/>
    <?php echo $this->translate("Customer"); ?>
</a>