<div class="message-warning">
    <?php echo $this->translate('Do you want to delete this node?'); ?>
    &nbsp;&nbsp;
    <a title="<?php echo $this->translate('Yes'); ?>" href="<?php echo $this->url(array('accept' => 1)); ?>"><?php echo $this->translate('Yes'); ?></a>
    &nbsp;
    <a title="<?php echo $this->translate('No'); ?>" href="<?php echo $this->url(array('accept' => 0)); ?>"><?php echo $this->translate('No'); ?></a>
</div>