<tr>
    <td><a title="<?php echo $this->translate('Edit'); ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $this->id)); ?>"><?php echo $this->name; ?></a></td>
    <td><?php echo $this->qouta; ?></td>
    <td><?php echo $this->bandwidth; ?></td>
    <td>
        <?php
        if($this->reseller) {
            $src = $this->baseUrl().'/sites/office-web-admin/images/icons/16/aspnet/tick-green.gif';
        } else {
            $src = $this->baseUrl().'/sites/office-web-admin/images/icons/16/aspnet/tick-red.gif';
        }
        ?>
        <img alt="<?php echo $this->translate('Reseller'); ?>" src="<?php echo $src; ?>" />
    </td>
    <td><?php echo $this->cost_per_month; ?></td>
    <td><?php echo ($this->cost_per_month * 11); ?></td>
    <td>
        <a title="<?php echo $this->translate('Edit'); ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $this->id)); ?>"><img alt="<?php echo $this->translate('Edit'); ?>" src="<?php echo $this->baseUrl().'/sites/office-web-admin/images/icons/16/aspnet/edit.gif'; ?>" /></a>
        <a title="<?php echo $this->translate('Delete'); ?>" href="<?php echo $this->url(array('action' => 'delete', 'id' => $this->id)); ?>"><img alt="<?php echo $this->translate('Delete'); ?>" src="<?php echo $this->baseUrl().'/sites/office-web-admin/images/icons/16/aspnet/delete.gif'; ?>" /></a>
    </td>
</tr>