<div class="advertismentbox">
    <img src="/files/monasebat.com/ads/<?php echo $this->image; ?>" alt="<?php echo $this->title; ?>" title="<?php echo $this->decsribe; ?>" /><br/>
    <?php echo $this->translate("Title"); ?>: <?php echo $this->title; ?><br/>
    <?php echo $this->translate("Link"); ?>: <?php echo $this->link; ?><br/>
    <?php echo $this->translate("Describe"); ?>: <?php echo $this->describe; ?><br/>
    <div class="tools">
        <a class="icon-edit" title="<?php echo $this->translate("Edit"); ?>" href="<?php echo $this->url(array('action'=>'edit', 'id' => $this->id)); ?>"></a>
        <a class="icon-delete" title="<?php echo $this->translate("Delete"); ?>" href="<?php echo $this->url(array('action'=>'delete', 'id' => $this->id)); ?>"></a>
    </div>
</div>